apiVersion: v1
description: External (not on K8s) NEO4J monitoring using Prometheus-operator and Grafana
name: neo4j-monitoring
version: 0.1.0
keywords:
  - grafana
  - prometheus
  - prometheus-operator
  - neo4j
home: https://github.com/skyscrapers/charts/
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
