apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fah-client.fullname" . }}
  labels:
    {{- include "fah-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fah-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fah-client.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fah-client.serviceAccountName" . }}
      priorityClassName: {{ include "fah-client.fullname" . }}
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USER
              value: {{ .Values.fahConfig.user | quote }}
            - name: TEAM
              value: {{ .Values.fahConfig.team | quote }}
            - name: PASSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fah-client.fullname" . }}
                  key: passkey
            - name: POWER
              value: {{ .Values.fahConfig.power | quote }}
            - name: GPU
              value: {{ .Values.fahConfig.gpu | quote }}
          volumeMounts:
            - mountPath: /home/fah
              name: data-volume
          ports:
            - name: http
              containerPort: 7396
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 7396
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
