apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "fah-client.fullname" . }}
value: {{ .Values.priorityClassValue }}
globalDefault: false
description: "This priority class should be used for Folding@Home (fah) Pods only."
