apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fah-client.fullname" . }}
  labels:
    {{- include "fah-client.labels" . | nindent 4 }}
data:
  passkey: {{ .Values.fahConfig.passkey | b64enc | quote }}
