apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "elasticache-monitoring.fullname" . }}
  labels:
{{ include "elasticache-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  groups:
    - name: elasticache-monitoring.rules
      rules:
        - alert: ElastiCacheMemoryUsageIsHigh
          annotations:
            message: 'ElastiCache memory usage on {{`{{$labels.cache_cluster_id}}`}} in cluster is higher than 90%'
          expr: aws_elasticache_database_memory_usage_percentage_maximum{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} {{ include "elasticache-monitoring.filterOnTag" . }} > 90
          for: 10m
          labels:
{{ include "elasticache-monitoring.alertLabels" . | indent 12 }}
            severity: warning
        - alert: ElastiCacheCPUUsage
          annotations:
            message: 'ElastiCache CPU utilization on {{`{{$labels.cache_cluster_id}}`}} in cluster is over than 90%'
          expr: aws_elasticache_cpuutilization_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} {{ include "elasticache-monitoring.filterOnTag" . }} >= 90
          for: 10m
          labels:
{{ include "elasticache-monitoring.alertLabels" . | indent 12 }}
            severity: warning
        - alert: ElastiCacheEvictions
          annotations:
            message: 'ElastiCache is evicting data on {{`{{$labels.cache_cluster_id}}`}}'
          expr: aws_elasticache_evictions_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} {{ include "elasticache-monitoring.filterOnTag" . }} > 0
          for: 10m
          labels:
{{ include "elasticache-monitoring.alertLabels" . | indent 12 }}
            severity: warning
