Dex:
  Issuer: https://kubesignin.test.skyscrape.rs/dex
  Connectors:
    GitHub:
    - Name: GitHub
      ClientId: <BASE64_ENCODED_CLIENT_ID>
      ClientSecret: <BASE64_ENCODED_CLIENT_SECRET>
      Org: skyscrapers

Kubesignin:
  ClientSecret: <SOME_RANDOM_STRING>
  RedirectUri: https://kubesignin.test.skyscrape.rs/callback
  DomainName: kubesignin.test.skyscrape.rs

# Kube2iam
host:
  iptables: true
  interface: cali+

# Kube-lego
config:
  LEGO_EMAIL: hello@skyscrapers.eu
  LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

# Nginx-ingress
controller:
  image:
    tag: "0.9.0-beta.7"
  publishService:
    enabled: true
  rbac:
    enabled: true
  stats:
    enabled: true
  config:
    use-proxy-protocol: "true"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'

ExternalDNS:
  IAMRoleARN: <IAM_ROLE_ARN>

concourse:
  imageTag: '3.3.1'
  externalURL: 'https://ci.kops.internal-test.skyscrape.rs'
  atcDomainName: 'ci.kops.internal-test.skyscrape.rs'
  tsaDomainName: 'tsa.ci.kops.internal-test.skyscrape.rs'
  username: ''
  password: ''
  keysS3Bucket: 's3://concourse-keys-internal-test/'
  githubAuthClientId: 'clientid'
  githubAuthClientSecret: 'clientsecret'
  githubAuthTeam: 'customer_org/ci,skyscrapers/skyscrapers'
  IAMRoleARN: 'arn:aws:iam::0123456789:role/kube2iam/concourse'
  postgresql:
    host: 'concourse.cdejtlq8mkct.eu-west-1.rds.amazonaws.com'
    database: 'concourse'
    postgresUser: 'concourse'
    postgresPassword: 'something'
