apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" $ | indent 4 }}
    {{- range $key, $val := .Values.prometheus.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  endpoints:
  - interval: {{ .Values.esExporterScrapeInterval }}
    scrapeTimeout: {{ .Values.esExporterScrapeTimeout }}
    port: http
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app: elasticsearch-exporter
      release: "{{ .Release.Name }}"

{{- if .Values.amazonService.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-cw"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" $ | indent 4 }}
    {{- range $key, $val := .Values.prometheus.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  endpoints:
  - interval: {{ .Values.amazonService.interval }}
    port: http
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app: prometheus-cloudwatch-exporter
      release: "{{ .Release.Name }}"
{{- end }}
