apiVersion: v1
description: Manifests, dashboards, and alerting rules for end-to-end Kubernetes cluster monitoring.
engine: gotpl
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
  - name: Michael Goodness
    email: mgoodness@gmail.com
name: kube-prometheus
sources:
  - https://github.com/coreos/prometheus-operator
  - https://github.com/kubernetes/charts
  - https://github.com/skyscrapers/charts
version: 0.0.1
