apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.ExternalDNS.IAMRoleARN }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - name: {{ template "fullname" . }}
        image: registry.opensource.zalan.do/teapot/external-dns:v0.3.0
        args:
          - --source=service
          - --source=ingress
          - --provider=aws
          - --registry=txt
          - --txt-owner-id=external-dns-{{ .Values.ExternalDNS.TXTOwnerId }}
