apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubesignin.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "kubesignin"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if .Values.Kubesignin.NodePort }}
  type: NodePort
{{- end }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
{{- if .Values.Kubesignin.NodePort }}
    nodePort: {{.Values.Kubesignin.NodePort}}
{{- end }}
  selector:
    app: {{ template "name" . }}
    component: kubesignin
    release: {{ .Release.Name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kubesignin.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "kubesignin"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: kubesignin
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "kubesignin.fullname" . }}
        image: {{.Values.Kubesignin.Image}}:{{.Values.Kubesignin.ImageTag}}

        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80

{{- if .Values.Dex.Tls }}
        volumeMounts:
        - name: tls
          mountPath: /etc/dex/tls
{{- end }}

        env:
        - name: DEX_ISSUER
          value: {{.Values.Dex.Issuer}}
{{- if .Values.Dex.Tls }}
        - name: DEX_CA
          value: /etc/dex/tls/tls.ca
{{- end }}
        - name: KUBESIGNIN_REDIRECT_URI
          value: {{.Values.Kubesignin.RedirectUri}}
        - name: KUBESIGNIN_LISTEN_ADDRESS
          value: "http://0.0.0.0:80"
        - name: KUBESIGNIN_CLIENT_ID
          value: kubesignin
        - name: KUBESIGNIN_CLIENT_SECRET
          value: {{.Values.Kubesignin.ClientSecret}}
{{- if .Values.Kubesignin.Debug }}
        - name: DEBUG
          value: true
{{- end }}

        resources:
          requests:
            cpu: {{ .Values.Kubesignin.Cpu }}
            memory: {{ .Values.Kubesignin.Memory }}
          limits:
            memory: {{ .Values.Kubesignin.Memory }}

      volumes:
{{- if .Values.Dex.Tls }}
      - name: tls
        secret:
          secretName: {{ template "dex.fullname" . }}.tls
{{- end }}
