{{- range $key, $value := .Values.proxies }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" $ }}-{{ $key }}
  labels:
    app: {{ template "name" $ }}-{{ $key }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.proxy.service.externalPort }}
      targetPort: {{ $.Values.proxy.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "name" $ }}-{{ $key }}
    release: {{ $.Release.Name }}
{{- end }}
