{{- if .Values.Kubesignin.K8sAdminsGroups }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
{{- range .Values.Kubesignin.K8sAdminsGroups }}
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
