apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "neo4j-monitoring.fullname" . }}
  labels:
{{ include "neo4j-monitoring.labels" . | indent 4 }}
subsets:
  - addresses:
      {{- range .Values.nodes }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - port: {{ .Values.metricsPort }}
        name: metrics
