apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "neo4j-monitoring.fullname" . }}
  labels:
{{ include "neo4j-monitoring.labels" . | indent 4 }}
subsets:
  - addresses:
      {{- range .Values.nodes }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - port: {{ .Values.neo4jMetricsPort }}
        name: metrics-neo4j
      {{ if .Values.nodeMetricsEnabled }}
      - port: {{ .Values.nodeMetricsPort }}
        name: metrics-node
      {{ end }}
