apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "neo4j-monitoring.fullname" . }}
  labels:
{{ include "neo4j-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  groups:
    - name: neo4j.rules
      rules: []
