apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j-monitoring.fullname" . }}
  labels:
{{ include "neo4j-monitoring.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.neo4jMetricsPort }}
      targetPort: {{ .Values.neo4jMetricsPort }}
      protocol: TCP
      name: metrics-neo4j
    {{ if .Values.nodeMetricsEnabled }}
    - port: {{ .Values.nodeMetricsPort }}
      targetPort: {{ .Values.nodeMetricsPort }}
      protocol: TCP
      name: metrics-node
    {{ end }}
