apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j-monitoring.fullname" . }}
  labels:
{{ include "neo4j-monitoring.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
      name: metrics
