# Prometheus MatchLabel selectors
prometheusSelectorLabels:
  prometheus: cluster-monitoring

scrapeInterval: "60s"

# SLA of the AmazonMQ broker to monitor.
# sla: production

## The following settings come from the prometheus-cloudwatch-exporter chart
# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/values.yaml
prometheus-cloudwatch-exporter:
  service:
    type: ClusterIP
    port: 80
    targetPort: 9100
    annotations: {}

  aws:
    stsRegional:
      enabled: true

  serviceAccount:
    create: true
    ## IRSA
    # annotations:
    #   eks.amazonaws.com/role-arn: <arn>
    #   eks.amazonaws.com/sts-regional-endpoints: "true"

  config: |-
    region: {{ .Values.aws.region }}
    period_seconds: 60
    set_timestamp: false
    metrics:
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: RabbitMQMemLimit
      aws_dimensions: [Node, Broker]
      aws_statistics: [Average]
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: RabbitMQMemUsed
      aws_dimensions: [Node, Broker]
      aws_statistics: [Maximum]
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: RabbitMQDiskFreeLimit
      aws_dimensions: [Node, Broker]
      aws_statistics: [Average]
    - aws_namespace: AWS/AmazonMQ
      aws_metric_name: RabbitMQDiskFree
      aws_dimensions: [Node, Broker]
      aws_statistics: [Minimum]

  serviceMonitor:
    enabled: false
