## Prometheus MatchLabel selectors
prometheus:
  labels:
    prometheus: "k8s-monitor"

## Interval for how often Prometheus scrapes the mongodb-exporter
interval: "30s"

mongodbExporter:
  ## number of exporter instances
  ##
  replicaCount: 1

  ## restart policy for all containers
  ##
  restartPolicy: Always

  image:
    repository: "skyscrapers/mongodb-exporter"
    tag: latest
    pullPolicy: IfNotPresent

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

  service:
    type: ClusterIP
    httpPort: 9001
    annotations: {}

  mongodb:
    ## username to connect to the mongodb server
    ##
    dbuser: foo
 
    ## password to connect to the mongodb server
    ##
    dbpass: bar
 
    ## Address (host and port) of the MongoDB replicaset we should connect to.
    ## Specify as <host>[:port][,<host>[<port>]] e.g., 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5:27019
    ##
    replicasetmembers: localhost
 
    ## If true, collect Mongodb Oplog status
    ##
    collectOplog: true

    ## If true, collect Mongodb replica set status
    ##
    collectReplSet: true

    ## If true, collect Mongodb Top metrics
    ##
    collectTopMetrics: false

    ## If true, collect MongoDB database metrics
    ##
    collectDatabaseMetrics: false

    ## If true, collect MongoDB collection metrics
    ##
    collectCollectionMetrics: false

    ## If true, collect MongoDB profile metrics
    ##
    collectProfileMetrics: false

    ## If true, collect MongoDB connpoolstats
    ##
    collectConnPoolStats: false
