# Default values for k8s-ec2-srcdst.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ottoyiu/k8s-ec2-srcdst
  tag: v0.2.2
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 64Mi

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Exists

affinity: {}

aws_region: eu-west-1
