apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "redshift-monitoring.fullname" . }}
  labels:
{{ include "redshift-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  groups:
  - name: redshift.rules
    rules:
    - alert: RedshiftExporterDown
      expr: up{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} != 1
      for: 5m
      labels:
        severity: critical
        group: persistence
      annotations:
        description: 'The Redshift metrics exporter for {{`{{ $labels.job }}`}} is down!'
        summary: Redshift monitoring is DOWN!
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-redshiftexporterdown'
    - alert: RedshiftHealthStatus
      expr: aws_redshift_health_status_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} != 1 and aws_redshift_maintenance_mode_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} == 0
      for: 5m
      labels:
        severity: critical
        group: persistence
      annotations:
        description: 'Redshift cluster is not healthy for {{`{{ $labels.cluster }}`}}!'
        summary: Redshift cluster is not healthy!
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-RedshiftHealthStatus'
    - alert: RedshiftMaintenanceMode
      expr: aws_redshift_maintenance_mode_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} != 0
      for: 5m
      labels:
        severity: warning
        group: persistence
        description: 'Redshift cluster is in maintenance mode for {{`{{ $labels.cluster }}`}}!'
        summary: Redshift cluster is in maintenance mode!
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-RedshiftMaintenanceMode'
    - alert: RedshiftLowDiskSpace
      expr: aws_redshift_percentage_disk_space_used_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} >= 95
      for: 15m
      labels:
        severity: warning
        group: persistence
      annotations:
        description: 'AWS Redshift cluster {{`{{ $labels.cluster }}`}} is low on free disk space'
        summary: AWS Redshift low disk
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-RedshiftLowDiskSpace'
    - alert: RedshiftSNoDiskSpace
      expr: aws_redshift_percentage_disk_space_used_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} >= 99
      for: 15m
      labels:
        severity: critical
        group: persistence
      annotations:
        description: 'AWS Redshift cluster {{`{{ $labels.cluster }}`}} is out of free disk space'
        summary: AWS Redshift low disk
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-redshfitlowdiskspace'
    - alert: RedshiftSCPUHigh
      expr: aws_redshift_cpuutilization_average{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"} >= 95
      for: 30m
      labels:
        severity: warning
        group: persistence
      annotations:
        description: 'AWS Redshift cluster {{`{{ $labels.cluster }}`}} is running at max CPU for 30 minutes'
        summary: AWS Redshift high CPU
        runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-redshiftcpuhigh'
