{{- if .Values.admissionController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
spec:
  ports:
    - port: 443
      name: http
      targetPort: 8000
    {{- if .Values.admissionController.servicemonitor.enabled }}
    - port: 8944
      name: metrics
      targetPort: 8944
    {{- end }}
  selector:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.selectorLabels" . | nindent 4 }}
{{- end }}
