{{- if .Values.admissionController.servicemonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
spec:
  ports:
    - port: 443
      targetPort: 8000
    - port: metrics
      targerPort: 8944
  selector:
    app.kubernetes.io/component: admission-controller
    {{- include "vpa.selectorLabels" . | nindent 4 }}
{{- end }}
