{{- if .Values.admissionController.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vpa.fullname" . }}-admission-controller
  labels:
    app.kubernetes.io/component: admission-controller
    prometheus: vertical-pod-autoscaler
    {{- include "vpa.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: {{ .Values.admissionController.servicemonitor.scrapeInterval }}
    port: metrics
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      {{- include "vpa.selectorLabels" . | nindent 6 }}
{{- end }}

