{{- if .Values.rbac.create }}

{{- if .Values.recommender.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-status-actor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-status-actor
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-checkpoint-actor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-checkpoint-actor
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:leader-locking-vpa-recommender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:leader-locking-vpa-recommender
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if .Values.updater.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-evictioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:evictioner
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-status-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-status-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:leader-locking-vpa-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:leader-locking-vpa-updater
subjects:
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if or .Values.recommender.enabled .Values.updater.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-actor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-actor
subjects:
{{- if .Values.recommender.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.updater.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

{{- if coalesce .Values.recommender.enabled .Values.updater.enabled .Values.admissionController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:vpa-target-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpa-target-reader
subjects:
{{- if .Values.recommender.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-recommender
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.admissionController.enabled}}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-admission-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.updater.enabled }}
  - kind: ServiceAccount
    name: {{ include "vpa.serviceAccountName" . }}-updater
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

{{- end }}
