name: elasticsearch-monitoring
version: 0.2.0
description: ElasticSearch monitoring using Prometheus-operator and Grafana.
keywords:
  - grafana
  - kube-prometheus
  - monitoring
  - prometheus
  - elasticsearch
home: https://github.com/skyscrapers/charts/
sources:
  - https://github.com/justwatchcom/elasticsearch_exporter
  - https://github.com/kubernetes/charts/tree/master/stable/elasticsearch-exporter
  - https://github.com/skyscrapers/charts
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
engine: gotpl
