apiVersion: v2
description: ElasticSearch monitoring using Prometheus-operator and Grafana.
name: elasticsearch-monitoring
type: application
version: 1.1.0
keywords:
  - grafana
  - kube-prometheus
  - monitoring
  - prometheus
  - elasticsearch
home: https://github.com/skyscrapers/charts/
sources:
  - https://github.com/justwatchcom/elasticsearch_exporter
  - https://github.com/kubernetes/charts/tree/master/stable/elasticsearch-exporter
  - https://github.com/skyscrapers/charts
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
engine: gotpl
dependencies:
  - name: elasticsearch-exporter
    version: 2.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus-cloudwatch-exporter
    version: 0.7.0
    repository: https://kubernetes-charts.storage.googleapis.com
