apiVersion: v2
description: ElasticSearch monitoring using Prometheus-operator and Grafana.
name: elasticsearch-monitoring
type: application
version: 1.7.0
keywords:
  - grafana
  - kube-prometheus
  - monitoring
  - prometheus
  - elasticsearch
home: https://github.com/skyscrapers/charts/
sources:
  - https://github.com/skyscrapers/charts
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
dependencies:
  - name: prometheus-elasticsearch-exporter
    version: 4.14.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-cloudwatch-exporter
    version: 0.19.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: amazonService
