dependencies:
  - name: elasticsearch-exporter
    version: 0.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus-cloudwatch-exporter
    version: 0.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
