dependencies:
  - name: elasticsearch-exporter
    version: 2.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: prometheus-cloudwatch-exporter
    version: 0.5.0
    repository: https://kubernetes-charts.storage.googleapis.com
