kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "k8s-ec2-srcdst.fullname" . }}
  labels:
    app: {{ include "k8s-ec2-srcdst.name" . }}
    chart: {{ include "k8s-ec2-srcdst.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role.kubernetes.io/networking: "1"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-ec2-srcdst.fullname" . }}
  labels:
    app: {{ include "k8s-ec2-srcdst.name" . }}
    chart: {{ include "k8s-ec2-srcdst.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role.kubernetes.io/networking: "1"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "k8s-ec2-srcdst.fullname" . }}
  labels:
    app: {{ include "k8s-ec2-srcdst.name" . }}
    chart: {{ include "k8s-ec2-srcdst.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role.kubernetes.io/networking: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ec2-srcdst.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ec2-srcdst.fullname" . }}
    namespace: {{ .Release.Namespace }}
