apiVersion: v1
kind: Service
metadata:
  name: {{ template "opsgenieHeartbeatProxy.fullname" . }}
  labels:
{{ include "labels" $ | indent 4 }}
    component: opsgenie-heartbeat-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.opsgenieHeartbeatProxy.port }}
  selector:
    app: {{ template "fullname" . }}
    component: "opsgenie-heartbeat-proxy"
    release: {{ .Release.Name }}
