{{- if .Values.enableVelero }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}-velero"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" $ | indent 4 }}
    prometheus: "{{ .Release.Name }}"
    app.kubernetes.io/component: velero
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: monitoring
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/instance: velero
{{- end }}
