apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opsgenieHeartbeatProxy.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    opsgenie_api_key: {{ .Values.opsgenieHeartbeatProxy.opsgenie_api_key | b64enc | quote }}