apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opsgenieHeartbeatProxy.fullname" . }}
  labels:
{{ include "labels" $ | indent 4 }}
    component: opsgenie-heartbeat-proxy
type: Opaque
data:
  opsgenie_api_key: {{ .Values.opsgenieHeartbeatProxy.opsgenie_api_key | b64enc | quote }}
