apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-calico"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: prometheus
    prometheus: k8s-monitor
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-calico-node"
      component: felix
