apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-calico"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" $ | indent 4 }}
    prometheus: "{{ .Release.Name }}"
    component: calico
spec:
  endpoints:
  - port: metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-calico-node"
      component: felix
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-autoscaler"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "labels" $ | indent 4 }}
    prometheus: "{{ .Release.Name }}"
    component: autoscaler
spec:
  endpoints:
  - port: http
    interval: 10s
  namespaceSelector:
    matchNames:
    - infrastructure
  selector:
    matchLabels:
      app: aws-cluster-autoscaler
      release: k8s-autoscaler
