apiVersion: v1
name: cluster-monitoring
version: 1.9.3
description: Cluster-wide monitoring setup using Prometheus-operator and Grafana.
keywords:
  - grafana
  - prometheus-operator
  - monitoring
  - prometheus
  - opsgenie
home: https://github.com/coreos/prometheus-operator/
sources:
  - https://github.com/coreos/prometheus-operator
  - https://github.com/helm/charts/tree/master/stable/prometheus-operator
  - https://github.com/skyscrapers/charts
maintainers:
  - name: skyscrapers
    email: hello@skyscrapers.eu
engine: gotpl
