dependencies:
- name: prometheus-operator
  version: 1.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus-cloudwatch-exporter
  version: 0.4.2
  repository: https://kubernetes-charts.storage.googleapis.com
