# Whether to create an "application-monitoring" namespace where you can add
# additional PrometheusRules and/or ServiceMonitors. This namespace will have a 
# `prometheus` label, which can be used with Prometheus' ruleNamespaceSelector
# and serviceMonitorNamespaceSelector
createMonitoringNamespace: false

# Whether to include the default dashboards (found in ./dashboards-default)
defaultDashboards: true

# Specify which extra Grafana dashboards you want to include (found in 
# ./dashboards-extra)
extraDashboards: []
# - mongodb
# - sqs
# - webapp

# Whether to enable the Calico ServiceMonitor & PrometheusRule
enableCalico: true

# Whether to enable the NodeLocal DNSCache ServiceMonitor
enableNodeLocalDNS: false
