# Whether to create an "application-monitoring" namespace where you can add
# additional PrometheusRules and/or ServiceMonitors. This namespace will have a 
# `prometheus` label, which can be used with Prometheus' ruleNamespaceSelector
# and serviceMonitorNamespaceSelector
createMonitoringNamespace: false

# Whether to include the default dashboards (found in ./dashboards-default)
defaultDashboards: true

# Specify which extra Grafana dashboards you want to include (found in 
# ./dashboards-extra)
extraDashboards: []
# - mongodb
# - sqs
# - webapp

opsgenieHeartbeatProxy:
  image: "traumfewo/opsgenie-heartbeat-proxy"
  imageTag: "v0.0.3"
  port: "8080"
  replicas: 3
  resources:
    requests:
      cpu: "128m"
      memory: "128Mi"
  #opsgenie_api_key:
  #heartbeat_name:
