apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "app.fullname" . }}-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mongodb
subsets:
{{- range .Values.nodes }}
  - addresses:
      - ip: {{ . }}
    ports:
      - name: http
        port: 9216
        protocol: TCP
{{- end }}
