apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb-exporter.fullname" . }}
  labels:
{{ include "labels" $ | indent 4 }}
{{- if .Values.mongodbExporter.service.annotations }}
  annotations:
{{ toYaml .Values.mongodbExporter.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.mongodbExporter.service.type }}
  ports:
    - name: http
      port: {{ .Values.mongodbExporter.service.httpPort }}
      protocol: TCP
  selector:
    app: mongodb-exporter
    release: "{{ .Release.Name }}"
