apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "concourse-monitoring.fullname" . }}
  labels:
{{ include "concourse-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  groups:
    - name: concourse-monitoring.rules
      rules:
        - alert: ConcourseWorkersMismatch
          expr: concourse_workers_registered{state="stalled"} != 0
          for: 1h
          labels:
            severity: critical
            group: concourse
          annotations:
            message: 'There are stale Concourse workers for more than an hour'
            runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-concourseworkersmismatch'
        - alert: ConcourseWorkerCPUCreditBalanceLow
          expr: aws_ec2_cpucredit_balance_minimum{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"}  == 0 
          for: 5m  
          labels:
            severity: critical
            group: concourse
          annotations:
            message: 'The CPU credit balance for Concourse ASG is 0!'
            runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-concoursecpucreditbalancelow'
        - alert: ConcourseWorkerEBSIOBalanceLow
          expr: aws_ec2_ebsiobalance__minimum{job="{{ .Release.Name }}-prometheus-cloudwatch-exporter"}  == 0 
          for: 5m  
          labels:
            severity: critical
            group: concourse
          annotations:
            message: 'The EBS IO balance for the Concourse ASG is 0!'
            runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-concourseebsiobalancelow'


        - alert: ConcourseEndpointDown
          expr: probe_success{target="{{ .Values.concourse_url }}"} != 1
          for: 5m
          labels:
            severity: critical
            group: concourse
          annotations:
            message: 'Concourse endpoint is down'
            runbook_url: 'https://github.com/skyscrapers/documentation/tree/master/runbook.md#alert-name-concourseendpointdown'