apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: concourse-endpoint
  labels:
{{ include "concourse-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  endpoints:
    - port: http
      scheme: http
      path: "/probe"
      interval: {{ .Values.blackbox_scrape_interval }}
      scrapeTimeout: {{ .Values.blackbox_scrape_timeout }}
      params:
        module:
          - http_2xx
        target:
          - {{ .Values.concourse_url }}
      metricRelabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: target
          replacement: {{ .Values.concourse_url }}
        - targetLabel: monitoring_name
          replacement: concourse-monitoring
  jobLabel: concourse-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
