{
 "title": "Vault",
 "description": " ",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(probe_success{ monitoring_name=\"vault-monitoring\" }) by (monitoring_name)"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( irate(vault_token_lookup_count[5m]) > 0)",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( irate(vault_token_create_count[1m]) > 0)",
     "legendFormat": "Create"
    },
    {
     "expr": "sum( irate(vault_token_store_count[1m]) > 0)",
     "legendFormat": "Store"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Audit Log Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( irate(vault_audit_log_request[5m]) > 0)",
     "legendFormat": "Request "
    },
    {
     "expr": "sum( irate(vault_audit_log_response[5m]) > 0)",
     "legendFormat": "Response"
    },
    {
     "expr": "sum( irate(vault_core_handle_request[5m]) > 0)",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Auth Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( irate(vault_route_rollback_auth_token__sum[5m]) > 0)",
     "legendFormat": "auth_token"
    },
    {
     "expr": "sum( irate(vault_route_rollback_cubbyhole__sum[5m]) > 0)",
     "legendFormat": "cubbyhole"
    },
    {
     "expr": "sum( irate(vault_route_rollback_identity__sum[5m]) > 0)",
     "legendFormat": "identity"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Dynamodb backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Dynamodb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_dynamodb_get_count{pod=\"vault-1\"}[5m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(vault_dynamodb_list_count{pod=\"vault-1\"}[5m])",
     "legendFormat": "LIST"
    },
    {
     "expr": "rate(vault_dynamodb_put_count{pod=\"vault-1\"}[5m])",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}