{
 "title": "Concourse / Pipelines",
 "tags": [
  "concourse",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(concourse_builds_finished, pipeline)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduling: Full",
   "type": "graph",
   "description": "Last time taken to schedule an entire pipeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(concourse_scheduling_full_duration_seconds_total{pipeline=~\"$pipeline\"}) by(pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Scheduling: Loading",
   "type": "graph",
   "description": "Last time taken to load version information from the database for a pipeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(concourse_scheduling_loading_duration_seconds_total{pipeline=~\"$pipeline\"}) by(pipeline)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "graph",
   "description": "Count of builds finished",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_finished{pipeline=~\"$pipeline\"}) by(pipeline, status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Build Duration",
   "type": "graph",
   "description": "Build time",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_builds_duration_seconds_sum{pipeline=~\"$pipeline\"}[5m]) / rate(concourse_builds_duration_seconds_count{pipeline=~\"$pipeline\"}[5m])) by(pipeline)",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}