{
 "title": "Neo4j",
 "description": "Neo4j cluster monitoring dashboard, with Prometheus data source.\nRead more at https://graphaware.com/neo4j/2019/06/11/monitoring-neo4j-prometheus.html",
 "tags": [ "neo4j" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(neo4j_bolt_accumulated_processing_time{endpoint=\"metrics\"}, job)"
   },
   {
    "name": "neo4j_instance",
    "label": "Neo4j Instance",
    "query": "label_values(neo4j_bolt_accumulated_processing_time{job=~\"$job\"}, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "$neo4j_instance Status",
   "type": "singlestat",
   "description": "Boolean status of the Neo4j server",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "neo4j_instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Counters of Graph Items",
   "type": "graph",
   "description": "Total number of graph items: node, relationships, ...",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_ids_in_use_(node|property|relationship)\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_ids_in_use_(.+)\")",
     "legendFormat": "# {{label}} {{instance}}"
    },
    {
     "expr": "neo4j_ids_in_use_relationship_type{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "# relationship type {{instance}}"
    }
   ]
  },
  {
   "title": "Graph Items Creation Rate (ids)",
   "type": "graph",
   "description": "Per-second Average Rate of Increase of Data Counters",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_ids_in_use_node{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Node rate {{instance}}"
    },
    {
     "expr": "rate(neo4j_ids_in_use_relationship{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Relationship rate {{instance}}"
    },
    {
     "expr": "rate(neo4j_ids_in_use_property{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "Property rate {{instance}}"
    }
   ]
  },
  {
   "title": "Node creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_node{job='$job', instance=\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Relationship creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_relationship{job=\"$job\", instance=\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Property creation speed (ids)",
   "type": "singlestat",
   "description": "This is in reality the change in neo4j ids.\nIf the transaction is rolled-back nodes will not be created but will increase this gauge.\n\nMaximum speed is set to 30k nodes/sec\nEmpirically we saw this is the maximum handled by the production machine",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(neo4j_ids_in_use_property{job='$job', instance=\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Last Closed Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_transaction_last_closed_tx_id_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Last Closed Write Transaction ID"
    }
   ]
  },
  {
   "title": "Committed Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_transaction_committed_total{job='$job', instance=\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Rolled back Transaction Speed",
   "type": "singlestat",
   "description": "Instant rate",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(neo4j_transaction_rollbacks_total{job=\"$job\", instance=\"$neo4j_instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "All transaction metrics",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_transaction_(started|committed|rollbacks|terminated)_total\", job='$job', instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_transaction_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Committed transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Total Committed Tr.s {{instance}}"
    },
    {
     "expr": "neo4j_transaction_committed_read_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Committed Read Tr.s {{instance}}"
    }
   ]
  },
  {
   "title": "Last Committed Write Transaction ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "neo4j_transaction_last_committed_tx_id_total{job='$job', instance=\"$neo4j_instance\"}",
     "legendFormat": "Last Committed Transaction ID"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "graph",
   "description": "Active Transactions - Read and Write - \nand Peak concurrent",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_transaction_active_read{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "Active read {{instance}}"
    },
    {
     "expr": "neo4j_transaction_active_write{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "Active write {{instance}}"
    },
    {
     "expr": "neo4j_transaction_peak_concurrent_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "Peak concurrent {{instance}}"
    }
   ]
  },
  {
   "title": "Committed Read Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_read_total{job='$job', instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Committed Write Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_write_total{job='$job', instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "Committed Transaction Rate",
   "type": "graph",
   "description": "Per-second average rate of increase of Committed Transactions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "rate {{instance}}"
    },
    {
     "expr": "irate(neo4j_transaction_committed_total{job='$job', instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "iRate {{instance}}"
    }
   ]
  },
  { "title": "Custom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Custom metric my-timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_graphaware_neo4j_monitoring_MonitorProcedure_my_timer * 10000"
    }
   ]
  },
  {
   "title": "Custom metric my-counter rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(com_graphaware_neo4j_monitoring_MonitorProcedure_my_counter[$interval])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  { "title": "Bolt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Bolt Messages (done vs failed)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_(done|failed)_total\", job='$job', instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Messages Queue",
   "type": "graph",
   "description": "Messages received - Messages started",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_bolt_messages_received_total{job='$job', instance=~\"$neo4j_instance\"} - neo4j_bolt_messages_started_total{job='$job', instance=~\"$neo4j_instance\"}",
     "legendFormat": "Bolt Msg Queue Length {{instance}}"
    },
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_messages_(received|started)_total\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_messages_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Rate of message queue time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_queue_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_connections_.+\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_connections_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_bolt_sessions.+\",  job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_bolt_sessions_(.+)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bolt rate of message processing time",
   "type": "graph",
   "description": "Processing and Queuing time per bolt message",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_bolt_accumulated_processing_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Page Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Page cache faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_page_faults_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache faults/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_page_faults_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache Pins and Unpins rate (pins/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_pins_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "pins {{instance}}"
    },
    {
     "expr": "rate(neo4j_page_cache_unpins_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "unpins {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions rate (evictions/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_evictions_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "evictions{{instance}}"
    },
    {
     "expr": "rate(neo4j_page_cache_eviction_exceptions_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "eviction exceptions {{instance}}"
    }
   ]
  },
  {
   "title": "Page cache evictions",
   "type": "graph",
   "description": "Eviction process in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_evictions_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache flushes",
   "type": "graph",
   "description": "The total number of flushes executed by the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_flushes_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits",
   "type": "graph",
   "description": "The total number of page hits happened in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hits_total{job='$job'}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Page Cache Hits Rate (hits/sec)",
   "type": "graph",
   "description": "Per-second Neo4j Page Cache Hits",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_hits_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page cache flushes rate (flushes/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_page_cache_flushes_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page Cache Hit Ratio",
   "type": "graph",
   "description": "The ratio of hits to the total number of lookups in the page cache",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_page_cache_hit_ratio{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Neo4j Log Rotation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_log_.+\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "graph",
   "description": "Neo4j Checkpoints. \nCheckpointing is the process of flushing all pending page updates from the page cache to the store files",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"neo4j_check_point_(events|total_time)_total\", job=\"$job\", instance=~\"$neo4j_instance\"}, \"label\", \"$1\", \"__name__\", \"neo4j_(.*)\")",
     "legendFormat": "{{label}} {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint event duration sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "neo4j_check_point_check_point_duration{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "VM Garbage Collector",
   "type": "graph",
   "description": "Time and counters",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vm_gc_time_g1_.+_generation_total\", job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    },
    {
     "expr": "delta(vm_gc_time_g1_old_generation_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "delta g1 old g total {{instance}}"
    },
    {
     "expr": "delta(vm_gc_time_g1_young_generation_total{job=\"$job\", instance=~\"$neo4j_instance\"}[$interval])",
     "legendFormat": "delta g1 young g total {{instance}}"
    }
   ]
  },
  {
   "title": "VM Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_thread_count{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "vm live threads {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Heap Size",
   "type": "graph",
   "description": "Heap memory (eden space, old generation, survivor space)\nNon-heap memory (metaspace, compressed class space, code cache)",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"vm_memory_pool_g1_(eden|old|survivor).*\", job=\"$job\", instance=~\"$neo4j_instance\"}) by (instance)",
     "legendFormat": "{{instance}} heap"
    },
    {
     "expr": "sum({__name__=~\"vm_memory_pool_(code|compressed|metaspace).*\", job=\"$job\", instance=~\"$neo4j_instance\"}) by (instance)",
     "legendFormat": "{{instance}} non-heap"
    }
   ]
  },
  {
   "title": "JVM Used Buffer rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 118 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vm_memory_buffer_direct_used{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "memory buffer direct used {{instance}}"
    },
    {
     "expr": "vm_memory_buffer_mapped_used{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "memory buffer mapped used{{instance}}"
    }
   ]
  },
  { "title": "Causal Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Committed read transaction rate - neo4j_instance Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_read_total{job=\"$job\", instance=\"$neo4j_instance\"}[$interval])",
     "legendFormat": "neo4j_instance {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_read_total{job=\"$job\", instance!=\"$neo4j_instance\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Committed write transaction rate - neo4j_instance Vs Others",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_transaction_committed_write_total{job=\"$job\", instance=\"$neo4j_instance\"}[$interval])",
     "legendFormat": "neo4j_instance {{instance}}"
    },
    {
     "expr": "sum(rate(neo4j_transaction_committed_write_total{job=\"$job\", instance!=\"$neo4j_instance\"}[$interval]))",
     "legendFormat": "Others sum"
    }
   ]
  },
  {
   "title": "Replicate pulls rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(neo4j_causal_clustering_read_replica_pull_updates_total[$interval])"
    }
   ]
  },
  {
   "title": "Core message processing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer{job=\"$job\", instance=~\"$neo4j_instance\"} * 10000",
     "legendFormat": "{{quantile}} {{instance}}"
    }
   ]
  },
  {
   "title": "Core election timeout ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer_election_timeout{job=\"$job\", instance=~\"$neo4j_instance\", quantile=\"0.5\"} * 10000",
     "legendFormat": "median {{instance}}"
    },
    {
     "expr": "neo4j_causal_clustering_core_message_processing_timer_election_timeout_count{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  { "title": "Cypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Cyper replan events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neo4j_cypher_replan_events_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "Cyper wait time",
   "type": "graph",
   "description": "The total number of seconds waited between query replans",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "neo4j_cypher_replan_wait_time_total{job=\"$job\", instance=~\"$neo4j_instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } }
 ]
}