{
 "title": "Concourse / Overview",
 "tags": [ "concourse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Builds Started",
   "type": "singlestat",
   "description": "Total number of Concourse builds started",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_started_total)"
    }
   ]
  },
  {
   "title": "Builds Finished",
   "type": "singlestat",
   "description": "Total number of Concourse builds finished",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_finished_total)"
    }
   ]
  },
  {
   "title": "Builds Succeeded",
   "type": "singlestat",
   "description": "Total number of Concourse builds succeeded",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_succeeded_total)"
    }
   ]
  },
  {
   "title": "Builds Aborted",
   "type": "singlestat",
   "description": "Total number of Concourse builds aborted",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_aborted_total)"
    }
   ]
  },
  {
   "title": "Builds Errored",
   "type": "singlestat",
   "description": "Total number of Concourse builds errored",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_errored_total)"
    }
   ]
  },
  {
   "title": "Builds Failed",
   "type": "singlestat",
   "description": "Total number of Concourse builds failed",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(concourse_builds_failed_total)"
    }
   ]
  },
  {
   "title": "Builds Started / Finished",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_builds_started_total)",
     "legendFormat": "Started"
    },
    {
     "expr": "max(concourse_builds_finished_total)",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "HTTP Response Duration",
   "type": "graph",
   "description": "HTTP response duration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(concourse_http_responses_duration_seconds_sum[5m]) / rate(concourse_http_responses_duration_seconds_count[5m]))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Worker Containers",
   "type": "graph",
   "description": "Number of containers per worker",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_containers) by(worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Worker Volumes",
   "type": "graph",
   "description": "Number of volumes per worker",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_volumes) by(worker)",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "description": "Current number of concourse database connections",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_db_connections) by(dbname)",
     "legendFormat": "{{ dbname }}"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "description": "Recent number of Concourse database queries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_db_queries_total)",
     "legendFormat": "Queries"
    }
   ]
  }
 ]
}