{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard. \r\nWorks well with https://github.com/dcu/mongodb_mongod_exporter\r\n\r\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "mongodb" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": "label_values(mongodb_mongod_connections{state=\"current\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_mongod_instance_uptime_seconds{instance=~\"$env\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongod_connections{instance=~\"$env\",state=\"current\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongod_connections{instance=~\"$env\",state=\"available\"}"
    }
   ]
  },
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "env" },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_state{instance=~\"$env\"}",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}