apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aws-rabbitmq-monitoring.fullname" . }}
  labels:
{{ include "aws-rabbitmq-monitoring.labels" . | indent 4 }}
    {{- range $key, $val := .Values.prometheusSelectorLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  endpoints:
  - interval: {{ .Values.scrapeInterval }}
    port: http
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      app: prometheus-cloudwatch-exporter
      release: {{ .Release.Name }}
